package br.com.jbProjects.processor;

import br.com.jbProjects.builder.ProjectionTypedQueryBuilder;
import br.com.jbProjects.processor.query.ProjectionQuery;
import io.hypersistence.utils.hibernate.query.SQLExtractor;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Tuple;
import jakarta.persistence.TypedQuery;
import lombok.extern.slf4j.Slf4j;
import org.hibernate.engine.jdbc.internal.BasicFormatterImpl;
import org.hibernate.engine.jdbc.internal.Formatter;

/**
 * Created by julio.bueno on 12/03/2026.
 * <p>Debug and development utilities for ProjectionQuery.</p>
 *
 * <p>This class provides debugging tools for analyzing and previewing SQL queries
 * generated by {@link ProjectionQuery}. The primary feature is SQL preview, which
 * allows developers to see the exact SQL that will be executed without running
 * the query against production data.
 *
 * <p><b>Two Operating Modes:</b>
 *
 * <p><b>1. Enhanced Mode (Recommended):</b><br>
 * When Hypersistence Utils is available on the classpath, SQL is extracted directly
 * from the query plan without executing any database operations.
 *
 * <p><b>Advantages:</b>
 * <ul>
 *   <li>Zero performance overhead - no database access</li>
 *   <li>No transaction required</li>
 *   <li>Returns formatted SQL instantly</li>
 *   <li>Safe to use in any environment</li>
 * </ul>
 *
 * <p><b>Setup:</b>
 * <pre>{@code
 * <dependency>
 *     <groupId>io.hypersistence</groupId>
 *     <artifactId>hypersistence-utils-hibernate-63</artifactId>
 *     <version>3.15.2</version>
 * </dependency>
 * }</pre>
 *
 * <p><b>2. Basic Mode (Fallback):</b><br>
 * When Hypersistence Utils is not available, the query is executed with
 * {@code LIMIT 1} to force SQL generation and logging.
 *
 * <p><b>Characteristics:</b>
 * <ul>
 *   <li>Executes query and fetches 1 row</li>
 *   <li>Requires active database connection</li>
 *   <li>Minimal performance impact (single row fetch)</li>
 *   <li>SQL appears in logs</li>
 * </ul>
 *
 * <p><b>Setup:</b>
 * <pre>
 * logging.level.org.hibernate.SQL=DEBUG
 * or (for Spring Boot)
 * spring.jpa.show-sql=true
 * </pre>
 *
 * <p><b>Usage Example:</b>
 * <pre>{@code
 * // Create debug processor
 * ProjectionProcessorDebug debug = new ProjectionProcessorDebug(entityManager);
 *
 * // Build query
 * ProjectionQuery<Customer, CustomerDTO> query = ProjectionQuery
 *     .fromTo(Customer.class, CustomerDTO.class)
 *     .filter("age", ProjectionFilterOperator.GREATER_THAN, 18)
 *     .order("name", OrderDirection.ASC)
 *     .paging(0, 20);
 *
 * // Preview SQL
 * String sql = debug.previewSQL(query);
 * System.out.println(sql);
 * }</pre>
 *
 * <p><b>Output Example (Enhanced Mode):</b>
 * <pre>{@code
 * SELECT
 *     c1_0.id,
 *     c1_0.name,
 *     c1_0.age
 * FROM
 *     customer c1_0
 * WHERE
 *     c1_0.age > ?
 * ORDER BY
 *     c1_0.name
 * LIMIT ?
 * }</pre>
 *
 * <p><b>Thread Safety:</b> This class is thread-safe. Each instance maintains
 * its own {@link ProjectionProcessor} and {@link Formatter}.
 *
 * <p><b>Performance Considerations:</b>
 * <ul>
 *   <li>Enhanced Mode: ~0.1ms per preview (no database access)</li>
 *   <li>Basic Mode: Database query time + 1 row fetch</li>
 * </ul>
 *
 * <p><b>Important:</b> This class is intended for development and debugging only.
 * Do not use in production code paths or performance-critical sections.
 *
 * @see ProjectionProcessor
 * @see ProjectionQuery
 */
@Slf4j
public class ProjectionProcessorDebug {

    private final ProjectionTypedQueryBuilder queryBuilder = new ProjectionTypedQueryBuilder();
    private final Formatter formatter = new BasicFormatterImpl();
    private final EntityManagerFactory entityManagerFactory;

    /**
     * Creates a new debug processor for the given EntityManager.
     *
     * @param entityManagerFactory the EntityManagerFactory used to create an EntityManager for query processing. Must not be null.
     * @throws IllegalArgumentException if entityManager is null
     */
    public ProjectionProcessorDebug(EntityManagerFactory entityManagerFactory) {
        this.entityManagerFactory = entityManagerFactory;
    }

    /**
     * Generates and returns SQL preview for the given projection query.
     *
     * <p>This method automatically detects which mode to use:
     * <ul>
     *   <li>If Hypersistence Utils is available: Uses {@link #extractSQLWithHypersistence(TypedQuery)}</li>
     *   <li>If not available: Falls back to {@link #fallbackToLogging(TypedQuery)}</li>
     * </ul>
     *
     * <p>The returned SQL is formatted for readability with proper indentation
     * and line breaks using Hibernate's {@link BasicFormatterImpl}.
     *
     * <p><b>Enhanced Mode Output:</b>
     * <pre>{@code
     * SELECT
     *     c1_0.id,
     *     c1_0.name
     * FROM
     *     customer c1_0
     * WHERE
     *     c1_0.status = ?
     * }</pre>
     *
     * <p><b>Basic Mode Output:</b>
     * <pre>
     * SQL preview generated via logging
     *
     * ┌───────────────────────────────────────────────────────────────┐
     * │  Current Mode: Query Execution (LIMIT 1)                      │
     * │  • Fetches 1 row from database                                │
     * │  ...                                                          │
     * └───────────────────────────────────────────────────────────────┘
     * </pre>
     *
     * @param projectionQuery The projection query to preview. Must not be null.
     * @return Formatted SQL string in Enhanced Mode, informational message in Basic Mode
     * @throws IllegalArgumentException if projectionQuery is null
     *
     * @see #extractSQLWithHypersistence(TypedQuery)
     * @see #fallbackToLogging(TypedQuery)
     */
    public String previewSQL(ProjectionQuery<?, ?> projectionQuery){
        try(EntityManager em = entityManagerFactory.createEntityManager()){
            TypedQuery<Tuple> typedQuery = queryBuilder.build(projectionQuery, em);

            try {
                return extractSQLWithHypersistence(typedQuery);

            } catch (NoClassDefFoundError e) {
                return fallbackToLogging(typedQuery);

            }
        }
    }

    /**
     * Extracts SQL using Hypersistence Utils (Enhanced Mode).
     *
     * <p>This method uses {@link SQLExtractor} from Hypersistence Utils to extract
     * the compiled SQL directly from the Hibernate query plan without executing
     * any database operations.
     *
     * <p>The extracted SQL is then formatted using Hibernate's {@link BasicFormatterImpl}
     * for better readability and logged at INFO level for debugging purposes.
     *
     * <p><b>Package-private visibility:</b> This method is intentionally package-private
     * to allow mocking in unit tests. Tests can mock this method to throw
     * {@link NoClassDefFoundError} and verify fallback behavior.
     *
     * <p><b>Performance:</b> Typically completes in ~0.1ms as it only accesses
     * Hibernate's query compilation metadata.
     *
     * @param typedQuery The TypedQuery to extract SQL from. Must not be null.
     * @return Formatted SQL string with proper indentation and line breaks
     * @throws NoClassDefFoundError if Hypersistence Utils is not on classpath
     * @throws NullPointerException if typedQuery is null
     */
    String extractSQLWithHypersistence(TypedQuery<?> typedQuery){
        org.hibernate.query.Query<?> hibernateQuery = typedQuery.unwrap(org.hibernate.query.Query.class);
        String sql = SQLExtractor.from(hibernateQuery);
        String formattedSQL = formatter.format(sql);
        log.info("Generated SQL:{}", formatter.format(formattedSQL));
        return formattedSQL;
    }

    /**
     * Fallback method for SQL preview when Hypersistence Utils is not available.
     *
     * <p>This method executes the query with {@code LIMIT 1} to force Hibernate
     * to compile and log the SQL statement. The query is actually executed against
     * the database, fetching one row, but the result is discarded.
     *
     * <p><b>Behavior:</b>
     * <ol>
     *   <li>Logs warning that Hypersistence Utils is not available</li>
     *   <li>Sets max results to 1 (LIMIT 1)</li>
     *   <li>Executes query (Hibernate logs SQL)</li>
     *   <li>Returns informational message with setup instructions</li>
     * </ol>
     *
     * <p><b>Database Impact:</b>
     * <ul>
     *   <li>Executes SELECT with LIMIT 1</li>
     *   <li>Fetches exactly 1 row (or 0 if no data)</li>
     *   <li>Minimal performance impact</li>
     *   <li>Requires active transaction and database connection</li>
     * </ul>
     *
     * <p><b>SQL Logging Requirements:</b>
     * To see the generated SQL in logs, ensure one of these is configured:
     * <pre>
     * # Option 1: Hibernate SQL logging
     * logging.level.org.hibernate.SQL=DEBUG
     *
     * # Option 2: Formatted SQL logging
     * spring.jpa.properties.hibernate.format_sql=true
     * logging.level.org.hibernate.SQL=DEBUG
     *
     * # Option 3: Show SQL in console (Spring Boot)
     * spring.jpa.show-sql=true
     * </pre>
     *
     * <p>The returned message includes instructions for:
     * <ul>
     *   <li>Adding Hypersistence Utils for zero-cost preview</li>
     *   <li>Configuring SQL logging to see the query</li>
     * </ul>
     *
     * @param typedQuery The TypedQuery to execute. Must not be null.
     * @return Informational message with setup instructions and current mode details
     * @throws jakarta.persistence.PersistenceException if query execution fails
     * @throws NullPointerException if typedQuery is null
     */
    private String fallbackToLogging(TypedQuery<?> typedQuery){
        log.warn("Hypersistence Utils is not available. Generating SQL via logging...");

        typedQuery.setMaxResults(1);
        typedQuery.getResultList();

        String message = """
            SQL preview generated via logging
            
            ┌───────────────────────────────────────────────────────────────┐
            │  Current Mode: Query Execution (LIMIT 1)                      │
            │  • Fetches 1 row from database                                │
            │  • Minimal performance impact                                 │
            │  • Requires active database connection                        │
            ├───────────────────────────────────────────────────────────────┤
            │  For Zero-Cost Preview:                                       │
            │  Add Hypersistence Utils dependency                           │
            │                                                               │
            │  <dependency>                                                 │
            │    <groupId>io.hypersistence</groupId>                        │
            │    <artifactId>hypersistence-utils-hibernate-63</artifactId>  │
            │    <version>3.15.2</version>                                  │
            │  </dependency>                                                │
            ├───────────────────────────────────────────────────────────────┤
            │  To See SQL in Logs:                                          │
            │  logging.level.org.hibernate.SQL=DEBUG                        │
            │  or                                                           │
            │  spring.jpa.properties.hibernate.format_sql=true              │
            └───────────────────────────────────────────────────────────────┘""";

        log.info(message);
        return message;
    }
}
